-- MySQL Script generated by MySQL Workbench
-- Sat Feb  3 15:59:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- TEST

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_GENERO` (
  `IdGenero` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IdGenero`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_TIPO_DOCUMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_TIPO_DOCUMENTO` (
  `Id_Tipo_Documento` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Tipo_Documento`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_PACIENTE` (
  `Id_Paciente` INT NOT NULL AUTO_INCREMENT,
  `Numero_Documento` INT NOT NULL,
  `Nombre` VARCHAR(80) NOT NULL,
  `Direccion` VARCHAR(80) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `IdGenero` INT NOT NULL,
  `Id_Tipo_Documento` INT NOT NULL,
  PRIMARY KEY (`Id_Paciente`),
  INDEX `FK_Paciente_Genero_idx` (`IdGenero` ASC),
  INDEX `FK_Paciente_TipoDocumento_idx` (`Id_Tipo_Documento` ASC),
  CONSTRAINT `FK_Paciente_Genero`
    FOREIGN KEY (`IdGenero`)
    REFERENCES `CLINICA_RED`.`TBL_GENERO` (`IdGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Paciente_TipoDocumento`
    FOREIGN KEY (`Id_Tipo_Documento`)
    REFERENCES `CLINICA_RED`.`TBL_TIPO_DOCUMENTO` (`Id_Tipo_Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_MS_ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_MS_ROLES` (
  `Id_Rol` INT NOT NULL AUTO_INCREMENT,
  `Rol` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Creado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Modificado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Rol`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_MS_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_MS_USUARIO` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `DNI` INT NOT NULL,
  `Usuario` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(80) NOT NULL,
  `Direccion` VARCHAR(80) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `FechaContratacion` DATETIME NOT NULL,
  `Estado_Usuario` INT NOT NULL,
  `Contrasena` VARCHAR(100) NOT NULL,
  `IdRol` INT NOT NULL,
  `IdGenero` INT NOT NULL,
  `Fecha_Ultima_Conexion` DATETIME NOT NULL,
  `Primer_Inicio_Sesion` DATETIME NOT NULL,
  `Fecha_Vencimiento` DATE NOT NULL,
  `Creado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Numero_Inicio_Sesion` INT NOT NULL,
  PRIMARY KEY (`Id_Usuario`),
  INDEX `FK_Empleado_Genero_idx` (`IdGenero` ASC),
  INDEX `FK_Usuario_Rol_idx` (`IdRol` ASC),
  CONSTRAINT `FK_Empleado_Genero`
    FOREIGN KEY (`IdGenero`)
    REFERENCES `CLINICA_RED`.`TBL_GENERO` (`IdGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Usuario_Rol`
    FOREIGN KEY (`IdRol`)
    REFERENCES `CLINICA_RED`.`TBL_MS_ROLES` (`Id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_TIPO_CITA`
-- -----------------------------------------------------
use clinica_red;
CREATE TABLE IF NOT EXISTS `TBL_TIPO_CITA` (
  `Id_Tipo_Cita` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Id_Tipo_Cita`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_CITA_TERAPEUTICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_CITA_TERAPEUTICA` (
  `id_Cita_Terapia` INT NOT NULL AUTO_INCREMENT,
  `Descripcion_Cita` VARCHAR(80) NOT NULL,
  `Fecha_Registro` DATETIME NOT NULL,
  `Fecha_Cita` DATE NOT NULL,
  `Hora_Cita` TIME NOT NULL,
  `Id_Paciente` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Id_Tipo_Cita` INT NOT NULL,
  `Id_Doctor` INT NOT NULL,
  PRIMARY KEY (`id_Cita_Terapia`),
  INDEX `FK_CitaTerapeutica_Paciente_idx` (`Id_Paciente` ASC),
  INDEX `FK_CitaTerapeutica_Empleado_idx` (`Id_Usuario` ASC),
  INDEX `fk_TBL_CITA_TERAPEUTICA_TBL_TIPO_CITA1_idx` (`Id_Tipo_Cita` ASC),
  INDEX `FK_CitaTerapeutica_Usuario_idx` (`Id_Doctor` ASC),
  CONSTRAINT `FK_CitaTerapeutica_Paciente`
    FOREIGN KEY (`Id_Paciente`)
    REFERENCES `TBL_PACIENTE` (`Id_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CitaTerapeutica_Empleado`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_CITA_TERAPEUTICA_TBL_TIPO_CITA1`
    FOREIGN KEY (`Id_Tipo_Cita`)
    REFERENCES `TBL_TIPO_CITA` (`Id_Tipo_Cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CitaTerapeutica_Usuario`
    FOREIGN KEY (`Id_Doctor`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_EXPEDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_EXPEDIENTE` (
  `id_Expediente` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Creacion` DATETIME NOT NULL,
  `id_Cita_Terapia` INT NOT NULL,
  `id_Usuario` INT NOT NULL,
  PRIMARY KEY (`id_Expediente`),
  INDEX `fk_TBL_EXPEDIENTE_TBL_CITA_TERAPEUTICA1_idx` (`id_Cita_Terapia` ASC),
  INDEX `fk_TBL_EXPEDIENTE_TBL_MS_USUARIO1_idx` (`id_Usuario` ASC),
  CONSTRAINT `fk_TBL_EXPEDIENTE_TBL_CITA_TERAPEUTICA1`
    FOREIGN KEY (`id_Cita_Terapia`)
    REFERENCES `TBL_CITA_TERAPEUTICA` (`id_Cita_Terapia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_EXPEDIENTE_TBL_MS_USUARIO1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_TIPO_TRATAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_TIPO_TRATAMIENTO` (
  `Id_Tipo_Tratamiento` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Id_Tipo_Tratamiento`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_TIPO_TERAPIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_TIPO_TERAPIA` (
  `idTipoTerapia` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Id_Tipo_Tratamiento` INT NOT NULL,
  PRIMARY KEY (`idTipoTerapia`),
  INDEX `FK_TipoTerapia_TipoTratamiento_idx` (`Id_Tipo_Tratamiento` ASC),
  CONSTRAINT `FK_TipoTerapia_TipoTratamiento`
    FOREIGN KEY (`Id_Tipo_Tratamiento`)
    REFERENCES `TBL_TIPO_TRATAMIENTO` (`Id_Tipo_Tratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_TIPO_DISTRIBUCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_TIPO_DISTRIBUCION` (
  `Id_Tipo_Distribucion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(10) NOT NULL,
  `Frecuencia` INT NOT NULL,
  PRIMARY KEY (`Id_Tipo_Distribucion`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_TERAPIA_EXPEDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_TERAPIA_EXPEDIENTE` (
  `Id_Terapia` INT NOT NULL AUTO_INCREMENT,
  `Numero_Sesiones` INT NOT NULL,
  `Id_Expediente` INT NOT NULL,
  `Id_Tipo_Terapia` INT NOT NULL,
  `Id_Tipo_Distribucion` INT NOT NULL,
  `Observacion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Terapia`),
  INDEX `FK_Terapia_TipoTerapia_idx` (`Id_Tipo_Terapia` ASC),
  INDEX `FK_Terapia_Expediente_idx` (`Id_Expediente` ASC),
  INDEX `fk_TBL_TERAPIA_TBL_TIPO_DISTRIBUCION1_idx` (`Id_Tipo_Distribucion` ASC),
  CONSTRAINT `FK_Terapia_TipoTerapia`
    FOREIGN KEY (`Id_Tipo_Terapia`)
    REFERENCES `TBL_TIPO_TERAPIA` (`idTipoTerapia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Terapia_Expediente`
    FOREIGN KEY (`Id_Expediente`)
    REFERENCES `TBL_EXPEDIENTE` (`id_Expediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_TERAPIA_TBL_TIPO_DISTRIBUCION1`
    FOREIGN KEY (`Id_Tipo_Distribucion`)
    REFERENCES `TBL_TIPO_DISTRIBUCION` (`Id_Tipo_Distribucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `TBL_DETALLE_TERAPIA` (
  `Id_Detalle_Terapia` INT NOT NULL AUTO_INCREMENT,
  `Duracion` TIME NOT NULL,
  `Fecha_Terapia` DATETIME NOT NULL,
  `Id_Cita_Terapia` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Id_Terapia` INT NOT NULL,
  PRIMARY KEY (`Id_Detalle_Terapia`),
  INDEX `FK_DetalleTerapia_Empleado_idx` (`Id_Usuario` ASC),
  INDEX `FK_DetalleTerapia_CitaTerapeutica_idx` (`Id_Cita_Terapia` ASC),
  INDEX `FK_DetalleTerapia_Terapia_idx` (`Id_Terapia` ASC),
  CONSTRAINT `FK_DetalleTerapia_Empleado`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DetalleTerapia_CitaTerapeutica`
    FOREIGN KEY (`Id_Cita_Terapia`)
    REFERENCES `TBL_CITA_TERAPEUTICA` (`id_Cita_Terapia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DetalleTerapia_Terapia`
    FOREIGN KEY (`Id_Terapia`)
    REFERENCES `TBL_TERAPIA_EXPEDIENTE` (`Id_Terapia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBL_TIPO_CONTACTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_TIPO_CONTACTO` (
  `Id_Tipo_Contacto` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Tipo_Contacto`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_CONTACTO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_CONTACTO_USUARIO` (
  `Id_Contacto_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Contacto_Usuario` VARCHAR(50) NOT NULL,
  `Id_Tipo_Contacto` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  INDEX `FK_Telefono_TipoTelefono_idx` (`Id_Tipo_Contacto` ASC),
  PRIMARY KEY (`Id_Contacto_Usuario`),
  INDEX `FK_ContactoUsuario_Usuario_idx` (`Id_Usuario` ASC),
  CONSTRAINT `FK_Telefono_TipoTelefono`
    FOREIGN KEY (`Id_Tipo_Contacto`)
    REFERENCES `TBL_TIPO_CONTACTO` (`Id_Tipo_Contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ContactoUsuario_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_PIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_PIN` (
  `Id_Pin` INT NOT NULL,
  `Pin` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Creado_Por` VARCHAR(15) NOT NULL,
  `Modificado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Pin`),
  INDEX `FK_PreguntasUsuario_Usuario_idx` (`Id_Usuario` ASC),
  CONSTRAINT `FK_PreguntasUsuario_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_MS_PARAMETROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_MS_PARAMETROS` (
  `Id_Parametro` INT NOT NULL AUTO_INCREMENT,
  `Parametro` VARCHAR(50) NOT NULL,
  `Valor` VARCHAR(100) NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Parametro`),
  INDEX `FK_Parametros_Usuario_idx` (`Id_Usuario` ASC),
  CONSTRAINT `FK_Parametros_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `CLINICA_RED`.`TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_MS_HIST_CONTRASENA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_MS_HIST_CONTRASENA` (
  `Id_Hist` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT NOT NULL,
  `Contrasena` VARCHAR(100) NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Hist`),
  INDEX `FK_Contrasena_Usuario_idx` (`Id_Usuario` ASC),
  CONSTRAINT `FK_Contrasena_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `CLINICA_RED`.`TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_MS_OBJETOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_MS_OBJETOS` (
  `Id_Objetos` INT NOT NULL AUTO_INCREMENT,
  `Objeto` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Tipo_Objeto` VARCHAR(15) NOT NULL,
  `Creado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Modificado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Objetos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CLINICA_RED`.`TBL_MS_PERMISOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLINICA_RED`.`TBL_MS_PERMISOS` (
  `Id_Permisos` INT NOT NULL AUTO_INCREMENT,
  `Id_Rol` INT NOT NULL,
  `Id_Objeto` INT NOT NULL,
  `Permiso_Insercion` CHAR(1) NOT NULL,
  `Permiso_Eliminacion` CHAR(1) NOT NULL,
  `Permiso_Actualizacion` CHAR(1) NOT NULL,
  `Permiso_Consultar` CHAR(1) NOT NULL,
  `Creado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Modificado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Permisos`),
  INDEX `FK_Permisos_Roles_idx` (`Id_Rol` ASC),
  INDEX `FK_Permisos_Objetos_idx` (`Id_Objeto` ASC),
  CONSTRAINT `FK_Permisos_Roles`
    FOREIGN KEY (`Id_Rol`)
    REFERENCES `CLINICA_RED`.`TBL_MS_ROLES` (`Id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Permisos_Objetos`
    FOREIGN KEY (`Id_Objeto`)
    REFERENCES `CLINICA_RED`.`TBL_MS_OBJETOS` (`Id_Objetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `TBL_CONTACTO_PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_CONTACTO_PACIENTE` (
  `Id_Contacto_Paciente` INT NOT NULL AUTO_INCREMENT,
  `Contacto_Paciente` VARCHAR(50) NOT NULL,
  `Id_Paciente` INT NOT NULL,
  `Id_Tipo_Contacto` INT NOT NULL,
  PRIMARY KEY (`Id_Contacto_Paciente`),
  INDEX `FK_ContactoPaciente_Paciente_idx` (`Id_Paciente` ASC),
  INDEX `FK_ContactoPaciente_TipoContacto_idx` (`Id_Tipo_Contacto` ASC),
  CONSTRAINT `FK_ContactoPaciente_Paciente`
    FOREIGN KEY (`Id_Paciente`)
    REFERENCES `TBL_PACIENTE` (`Id_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ContactoPaciente_TipoContacto`
    FOREIGN KEY (`Id_Tipo_Contacto`)
    REFERENCES `TBL_TIPO_CONTACTO` (`Id_Tipo_Contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_EVALUACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_EVALUACION` (
  `Id_Evaluacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_Evaluacion`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_DETALLE_EXPEDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_DETALLE_EXPEDIENTE` (
  `Id_Detalle_Expediente` INT NOT NULL,
  `Fecha_Evaluacion` DATE NOT NULL,
  `Hora_Evaluacion` TIME NOT NULL,
  `Id_Expediente` INT NOT NULL,
  `Id_Evaluacion` INT NOT NULL,
  PRIMARY KEY (`Id_Detalle_Expediente`),
  INDEX `FK_DetalleExpediente_Expediente_idx` (`Id_Expediente` ASC),
  INDEX `fk_TBL_DETALLE_EXPEDIENTE_TBL_EVALUACION1_idx` (`Id_Evaluacion` ASC),
  CONSTRAINT `FK_DetalleExpediente_Expediente`
    FOREIGN KEY (`Id_Expediente`)
    REFERENCES `TBL_EXPEDIENTE` (`id_Expediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DETALLE_EXPEDIENTE_TBL_EVALUACION1`
    FOREIGN KEY (`Id_Evaluacion`)
    REFERENCES `TBL_EVALUACION` (`Id_Evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_RESULTADO_EVALUACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_RESULTADO_EVALUACION` (
  `Id_Resultado_Evaluacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Id_Evaluacion` INT NOT NULL,
  PRIMARY KEY (`Id_Resultado_Evaluacion`),
  INDEX `fk_TBL_RESULTADO_EVALUACION_TBL_EVALUACION1_idx` (`Id_Evaluacion` ASC),
  CONSTRAINT `fk_TBL_RESULTADO_EVALUACION_TBL_EVALUACION1`
    FOREIGN KEY (`Id_Evaluacion`)
    REFERENCES `TBL_EVALUACION` (`Id_Evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_RESULTADO_EXPEDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_RESULTADO_EXPEDIENTE` (
  `Id_Resultado_Expediente` INT NOT NULL AUTO_INCREMENT,
  `Id_Resultado_Evaluacion` INT NOT NULL,
  `Id_Detalle_Expediente` INT NOT NULL,
  `Resultado` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`Id_Resultado_Expediente`),
  INDEX `FK_ResultadoExpediente_ResultadoEvaluacion_idx` (`Id_Resultado_Evaluacion` ASC),
  INDEX `FK_ResultadoExpediente_DetalleExpediente_idx` (`Id_Detalle_Expediente` ASC),
  CONSTRAINT `FK_ResultadoExpediente_ResultadoEvaluacion`
    FOREIGN KEY (`Id_Resultado_Evaluacion`)
    REFERENCES `TBL_RESULTADO_EVALUACION` (`Id_Resultado_Evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ResultadoExpediente_DetalleExpediente`
    FOREIGN KEY (`Id_Detalle_Expediente`)
    REFERENCES `TBL_DETALLE_EXPEDIENTE` (`Id_Detalle_Expediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_BITACORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_BITACORA` (
  `Id_Bitacora` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Id_Objeto` INT NOT NULL,
  `Accion` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Bitacora`),
  INDEX `FK_Bitacora_Usuario_idx` (`Id_Usuario` ASC),
  INDEX `FK_Bitacora_Objetos_idx` (`Id_Objeto` ASC),
  CONSTRAINT `FK_Bitacora_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Bitacora_Objetos`
    FOREIGN KEY (`Id_Objeto`)
    REFERENCES `TBL_MS_OBJETOS` (`Id_Objetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_DETALLE_TERAPIA_TRATAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_DETALLE_TERAPIA_TRATAMIENTO` (
  `IdDetalleTerapiaTratamiento` INT NOT NULL AUTO_INCREMENT,
  `Id_Detalle_Terapia` INT NOT NULL,
  `Id_Tipo_Tratamiento` INT NOT NULL,
  `Resultado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdDetalleTerapiaTratamiento`),
  INDEX `FK_TBL_DETALLE_TERAPIA_TRATAMIENTO_TBL_DETALLE_TERAPIA_idx` (`Id_Detalle_Terapia` ASC),
  CONSTRAINT `FK_DetalleTerapiaTratamiento_TipoTratamiento`
    FOREIGN KEY (`Id_Tipo_Tratamiento`)
    REFERENCES `TBL_TIPO_TRATAMIENTO` (`Id_Tipo_Tratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DetalleTerapiaTratamiento_DetalleTerapia`
    FOREIGN KEY (`Id_Detalle_Terapia`)
    REFERENCES `TBL_DETALLE_TERAPIA` (`Id_Detalle_Terapia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_DIA_FERIADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_DIA_FERIADO` (
  `Id_Dia_Feriado` INT NOT NULL AUTO_INCREMENT,
  `Dia_Feriado` DATE NOT NULL,
  `Creado_Por` VARCHAR(45) NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Modificado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Dia_Feriado`),
  INDEX `FK_DiaFeriado_Usuario_idx` (`Id_Usuario` ASC),
  CONSTRAINT `FK_DiaFeriado_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_OBSERVACION_FISIOTERAPEUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_OBSERVACION_FISIOTERAPEUTA` (
  `Id_Obs_Fisioterapeuta` INT NOT NULL,
  `Observaciones` VARCHAR(100) NULL,
  `Otro` VARCHAR(100) NULL,
  `id_Expediente` INT NOT NULL,
  PRIMARY KEY (`Id_Obs_Fisioterapeuta`),
  INDEX `fk_TBL_OBSERVACION_FISIOTERAPEUTA_TBL_EXPEDIENTE1_idx` (`id_Expediente` ASC),
  CONSTRAINT `fk_TBL_OBSERVACION_FISIOTERAPEUTA_TBL_EXPEDIENTE1`
    FOREIGN KEY (`id_Expediente`)
    REFERENCES `TBL_EXPEDIENTE` (`id_Expediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_ESTADO_CITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_ESTADO_CITA` (
  `Id_Estado_Cita` INT NOT NULL AUTO_INCREMENT,
  `Id_Cita_Terapia` INT NOT NULL,
  `Estado_Cita` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Estado_Cita`),
  INDEX `FK_EstadoCita_CitaTerapeutica_idx` (`Id_Cita_Terapia` ASC),
  CONSTRAINT `FK_EstadoCita_CitaTerapeutica`
    FOREIGN KEY (`Id_Cita_Terapia`)
    REFERENCES `TBL_CITA_TERAPEUTICA` (`id_Cita_Terapia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TBL_HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBL_HORARIO` (
  `Id_Horario` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT NOT NULL,
  `Hora_Entrada` TIME NOT NULL,
  `Hora_Salida` TIME NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Creado_Por` VARCHAR(15) NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  `Modificado_Por` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Id_Horario`),
  INDEX `FK_Horario_Usuario_idx` (`Id_Usuario` ASC),
  CONSTRAINT `FK_Horario_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `TBL_MS_USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET @@UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET @@FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET @@SQL_MODE=@OLD_SQL_MODE;
